[font]
size = 14

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zellij"

[window]
padding.x = 0
padding.y = 0
opacity = 1

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[terminal]
# [[hints.enabled]]
# binding = { key = "U", mods = "Control|Shift" }
# command = "xdg-open"
# hyperlinks = true
# mouse.enabled = true
# mouse.mods = "Control"
# post_processing = true
# persist = false
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
