#!/bin/bash
# Render a palette JSON (themes/palettes/*.json) into per-app color files
# under ~/.cache/theme-colors/ and reload the consumers:
#   - hyprland.lua    -> merged over defaults by hypr/colors.lua (hyprctl reload)
#   - quickshell.json -> watched live by quickshell Theme.qml (no restart needed)
#   - ags-colors.scss -> baked into the AGS bundle (rebuild + restart if active)
#
# Usage: apply-palette.sh <palette.json> [--generate-only]
#   --generate-only  write the files but skip all reloads/rebuilds
#                    (used by ags/build.sh to seed a default palette)

set -eu

PALETTE="${1:?usage: apply-palette.sh <palette.json> [--generate-only]}"
GENERATE_ONLY="${2:-}"
OUT="$HOME/.cache/theme-colors"

if ! command -v jq >/dev/null 2>&1; then
    echo "apply-palette: jq is required" >&2
    exit 1
fi
if [ ! -f "$PALETTE" ]; then
    echo "apply-palette: palette not found: $PALETTE" >&2
    exit 1
fi

mkdir -p "$OUT"

KEYS="base mantle crust text subtext0 subtext1 surface0 surface1 surface2 overlay0 \
blue lavender sapphire sky teal green yellow peach maroon red mauve pink flamingo rosewater"

get() { jq -r --arg k "$1" '.[$k]' "$PALETTE"; }

# Validate the palette has every key before touching any output.
for k in $KEYS; do
    v=$(get "$k")
    case "$v" in
        \#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]) ;;
        *) echo "apply-palette: bad or missing color '$k' in $PALETTE: $v" >&2; exit 1 ;;
    esac
done

# --- quickshell: the palette itself, watched by Theme.qml ------------------
cp "$PALETTE" "$OUT/quickshell.json"

# --- hyprland: lua table merged over colors.lua defaults -------------------
hexof() { get "$1" | tr -d '#'; }
cat > "$OUT/hyprland.lua" <<EOF
-- Generated by themes/apply-palette.sh from $(basename "$PALETTE") — do not edit.
return {
    background = "rgb($(hexof base))",
    foreground = "rgb($(hexof text))",
    color0     = "rgb($(hexof surface1))",
    color1     = "rgb($(hexof red))",
    color2     = "rgb($(hexof green))",
    color3     = "rgb($(hexof yellow))",
    color4     = "rgb($(hexof blue))",
    color5     = "rgb($(hexof pink))",
    color6     = "rgb($(hexof sky))",
    color7     = "rgb($(hexof mauve))",
}
EOF

# --- ags: scss variables baked into the bundle at build time ---------------
{
    echo "// Generated by themes/apply-palette.sh from $(basename "$PALETTE") — do not edit."
    for k in $KEYS; do
        echo "\$$k: $(get "$k");"
    done
    echo ''
    echo '// Opacity variants'
    echo '$main-background: rgba($base, 0.3);'
    echo '$border-color: rgba($subtext1, 0.2);'
} > "$OUT/ags-colors.scss"

echo "apply-palette: generated $OUT/{hyprland.lua,quickshell.json,ags-colors.scss} from $(basename "$PALETTE")"

[ "$GENERATE_ONLY" = "--generate-only" ] && exit 0

# --- reload consumers ------------------------------------------------------
if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null && echo "apply-palette: hyprland reloaded"
fi

# AGS bakes the colors into its bundle; rebuild, and restart it only if it
# is the active status bar (quickshell picks the JSON up live via file watch).
if command -v ags >/dev/null 2>&1 && [ -f "$HOME/.config/ags/build.sh" ]; then
    if (cd "$HOME/.config/ags" && ./build.sh >/dev/null 2>&1); then
        echo "apply-palette: ags bundle rebuilt"
        if grep -q ags "$HOME/.config/hypr/user_settings/statusbar.sh" 2>/dev/null; then
            "$HOME/.config/hypr/scripts/launchbar.sh" >/dev/null 2>&1 &
            echo "apply-palette: ags bar restarted"
        fi
    else
        echo "apply-palette: WARNING: ags bundle rebuild failed" >&2
    fi
fi
