adapter_name = /dev/dri/by-path/pci-0000:11:00.0-render
capture = wlr
cert = /home/sergiom/.config/sunshine-seat1/credentials/cacert.pem
csrf_allowed_origins = ["https://ridge:48990", "https://localhost:48990", "https://127.0.0.1:48990"]
file_apps = /home/sergiom/.config/hypr/sunshine-seat1/apps.json
file_state = /home/sergiom/.config/sunshine-seat1/state.json
global_prep_cmd = [{"do":"/home/sergiom/.config/hypr/sunshine-seat1/resize.sh","undo":""}]
log_path = /home/sergiom/.config/sunshine-seat1/sunshine.log
pkey = /home/sergiom/.config/sunshine-seat1/credentials/cakey.pem
port = 48989
sunshine_name = ridge-seat1
